import os
from os.path import join
from tkinter import *
from tkinter import ttk
import docx2txt
import docx
taraf = []
x1 = docx2txt.process("1.DAVET MEKTUBU.docx")
x2 = docx2txt.process("2.BİLGİLENDİRME TUTANAĞI.docx")
x3 = docx2txt.process("3.İLK OTURUM TUTANAĞI.docx")
x4 = docx2txt.process("4.İKİNCİ OTURUM TUTANAĞI.docx")
x5 = docx2txt.process("5.ANLAŞMA BELGESİ.docx")
x6 =docx2txt.process("6.SON TUTANAK.docx")
x7 = docx2txt.process("7.ARABULUCULUK SON TUTANAK GÖNDERİMİ ÜST YAZI.docx")
x8 = docx2txt.process("8.ARABULUCULUK BÜRO ÖDEME ÜST YAZI.docx")
x9 = docx2txt.process("9.ÖRNEK MAKBUZ.docx")
x10 = docx2txt.process("10.ÜCRET SÖZLEŞMESİ.docx")
x11 = docx2txt.process("12.DAVET MEKTUBU.docx")

def rClicker(e):
    try:
        def rClick_Copy(e, apnd=0):
            e.widget.event_generate('<Control-c>')

        def rClick_Cut(e):
            e.widget.event_generate('<Control-x>')

        def rClick_Paste(e):
            e.widget.event_generate('<Control-v>')

        e.widget.focus()

        nclst=[
               (' Kes', lambda e=e: rClick_Cut(e)),
               (' Kopyala', lambda e=e: rClick_Copy(e)),
               (' Yapıştır', lambda e=e: rClick_Paste(e)),
               ]

        rmenu = Menu(None, tearoff=0, takefocus=0)

        for (txt, cmd) in nclst:
            rmenu.add_command(label=txt, command=cmd)

        rmenu.tk_popup(e.x_root+40, e.y_root+10,entry="0")

    except TclError:
        print( ' - rClick menu, something wrong')
        pass

    return "break"


def rClickbinder(r):

    try:
        for b in [ 'Text', 'Entry', 'Listbox', 'Label']: #
            r.bind_class(b, sequence='<Button-3>',
                         func=rClicker, add='')
    except TclError:
        print( ' - rClickbinder, something wrong')
        pass

def display_text():
    global entry
    global string1
    global string2
    global string3
    global string4
    global string5
    string1 = yazı.get()
    string2 = yazı2.get()
    string3 = yazı3.get()
    string4 = yazı4.get()
    string5 = yazı5.get()
    window.destroy()
def display_text1():
    global tarafs
    taraf.append(t1.get())
    taraf.append(t2.get())
    taraf.append(t3.get())
    taraf.append(t4.get())
    taraf.append(t5.get())
    taraf.append(t6.get())
    taraf.append(t7.get())
    taraf.append(t8.get())
    tarafs=tarafs+1
    t1.delete(0, END)
    t1.insert(0, "")
    t2.delete(0, END)
    t2.insert(0, "")
    t3.delete(0, END)
    t3.insert(0, "")
    t4.delete(0, END)
    t4.insert(0, "")
    t5.delete(0, END)
    t5.insert(0, "")
    t6.delete(0, END)
    t6.insert(0, "")
    t7.delete(0, END)
    t7.insert(0, "")
    t8.delete(0, END)
    t8.insert(0, "")
tarafs=0
def display_text2():
    global aaa1
    global aaa2
    global aaa3
    global aaa4
    global aaa5
    aaa1 = gg.get()
    aaa2 = gg2.get()
    aaa3 = gg3.get()
    aaa4 = gg4.get()
    aaa5 = gg5.get()
    window2.destroy()
def display_text3():
    global dosyasss
    dosyasss = dosya1.get()
    window3.destroy()


def dur():
    window1.destroy()


window = Tk()
window.wm_attributes('-fullscreen','true')
window.option_add( "*font", "lucida 30 bold italic" )
window.geometry('500x500')
window.configure(background="white");
a = Label(window, text="Arabuluculuk Bürosu",justify=LEFT, anchor="w").grid(sticky="W",row=0, column=0)
b = Label(window, text="Büro Dosya Numarası",justify=LEFT, anchor="w").grid(sticky="W",row=1, column=0)
c = Label(window, text="Arabuluculuk Numarası",justify=LEFT, anchor="w").grid(sticky="W",row=2, column=0)
d = Label(window, text="Arabuluculuk Başvuru Tarihi",justify=LEFT, anchor="w").grid(sticky="W",row=3, column=0)
e = Label(window, text="Arabuluculuk Konusu Uyuşmazlık ",justify=LEFT, anchor="w").grid(sticky="W",row=4, column=0)
yazı = Entry(window, width=40)
yazı.bind('<Button-3>',rClicker, add='')
yazı.grid(row=0, column=1)
yazı.focus_set()
yazı2 = Entry(window, width=40)
yazı2.grid(row=1, column=1)
yazı2.bind('<Button-3>',rClicker, add='')
yazı2.focus_set()
yazı3 = Entry(window, width=40)
yazı3.grid(row=2, column=1)
yazı3.bind('<Button-3>',rClicker, add='')
yazı3.focus_set()
yazı4 = Entry(window, width=40)
yazı4.grid(row=3, column=1)
yazı4.bind('<Button-3>',rClicker, add='')
yazı4.focus_set()
yazı5 = Entry(window, width=40)
yazı5.bind('<Button-3>',rClicker, add='')
yazı5.grid(row=4, column=1)
yazı5.focus_set()
Button = ttk.Button(window, text="Taraf Bilgisi Adımına Geçiniz", width=50, command=display_text)
Button.grid(row=5, column=1)
window.mainloop()


window1 = Tk()
window1.wm_attributes('-fullscreen','true')
window1.option_add( "*font", "lucida 30 bold italic" )
window1.geometry('500x500')
window1.configure(background="white");
a1 = Label(window1, text="Ad ve Soyad",justify=LEFT, anchor="w").grid(sticky="W",row=0, column=0)
b1 = Label(window1, text="Ticaret Sicil Numarası",justify=LEFT, anchor="w").grid(sticky="W",row=1, column=0)
c1 = Label(window1, text="Adresi",justify=LEFT, anchor="w").grid(sticky="W",row=2, column=0)
c1 = Label(window1, text="E-posta",justify=LEFT, anchor="w").grid(sticky="W",row=3, column=0)
d1 = Label(window1, text="Vekil",justify=LEFT, anchor="w").grid(sticky="W",row=4, column=0)
e1 = Label(window1, text="T.C. Kimlik Numarası",justify=LEFT, anchor="w").grid(sticky="W",row=5, column=0)
f1 = Label(window1, text=" Cep Tel",justify=LEFT, anchor="w").grid(sticky="W",row=6, column=0)
g1 = Label(window1, text="Email",justify=LEFT, anchor="w").grid(sticky="W",row=7, column=0)
t1 = Entry(window1, width=40)
t1.bind('<Button-3>',rClicker, add='')
t1.grid(row=0, column=1)
t1.focus_set()
t2 = Entry(window1, width=40)
t2.bind('<Button-3>',rClicker, add='')
t2.grid(row=1, column=1)
t2.focus_set()
t3 = Entry(window1, width=40)
t3.bind('<Button-3>',rClicker, add='')
t3.grid(row=2, column=1)
t3.focus_set()
t4 = Entry(window1, width=40)
t4.bind('<Button-3>',rClicker, add='')
t4.grid(row=3, column=1)
t4.focus_set()
t5 = Entry(window1, width=40)
t5.bind('<Button-3>',rClicker, add='')
t5.grid(row=4, column=1)
t5.focus_set()
t6 = Entry(window1, width=40)
t6.bind('<Button-3>',rClicker, add='')
t6.grid(row=5, column=1)
t6.focus_set()
t7 = Entry(window1, width=40)
t7.bind('<Button-3>',rClicker, add='')
t7.grid(row=6, column=1)
t7.focus_set()
t8 = Entry(window1, width=40)
t8.bind('<Button-3>',rClicker, add='')
t8.grid(row=7, column=1)
t8.focus_set()
Button1 = ttk.Button(window1, text="Sıradaki Tarafı Giriniz", width=30, command=display_text1)
Button1.grid(row=8, column=1)
Button2 = ttk.Button(window1, text="Taraf Bilgilerini Girmeyi Bitir", width=30, command=dur)
Button2.grid(row=9, column=1)
tttt = Label(window1, text="Boş Bırakılacak yerlere nokta koyunuz.").grid(sticky="W",row=8, column=0)
window.mainloop()

window2 = Tk()
window2.wm_attributes('-fullscreen','true')
window2.geometry('500x500')
window2.option_add( "*font", "lucida 30 bold italic" )
window2.configure(background="white");
q = Label(window2, text="Arabuluculuk Bürosuna Başvuru Tarihi ",justify=LEFT, anchor="w").grid(sticky="W",row=0, column=0)
w = Label(window2, text="Arabulucunun Görevlendirildiği Tarih",justify=LEFT, anchor="w").grid(sticky="W",row=1, column=0)
j = Label(window2, text="Arabuluculuk Sürecinin Bittiği Tarih ",justify=LEFT, anchor="w").grid(sticky="W",row=2, column=0)
k = Label(window2, text="Son Tutanağın Düzenlendiği Yer",justify=LEFT, anchor="w").grid(sticky="W",row=3, column=0)
l = Label(window2, text="Son Tutanağın Düzenlendiği Tarih",justify=LEFT, anchor="w").grid(sticky="W",row=4, column=0)
gg = Entry(window2, width=40)
gg.bind('<Button-3>',rClicker, add='')
gg.grid(row=0, column=1)
gg.focus_set()
gg2 = Entry(window2, width=40)
gg2.bind('<Button-3>',rClicker, add='')
gg2.grid(row=1, column=1)
gg2.focus_set()
gg3 = Entry(window2, width=40)
gg3.bind('<Button-3>',rClicker, add='')
gg3.grid(row=2, column=1)
gg3.focus_set()
gg4 = Entry(window2, width=40)
gg4.bind('<Button-3>',rClicker, add='')
gg4.grid(row=3, column=1)
gg4.focus_set()
gg5 = Entry(window2, width=40)
gg5.bind('<Button-3>',rClicker, add='')
gg5.grid(row=4, column=1)
gg5.focus_set()
Button = ttk.Button(window2, text="Bilgileri Girdiyseniz Basın", width=50, command=display_text2)
Button.grid(row=5, column=1)
tarafs = Label(window2, text=tarafs).grid(row=6, column=1)
window2.mainloop()

window3 = Tk()
window3.wm_attributes('-fullscreen','true')
window3.geometry('500x500')
window3.configure(background="white");
dosya = Label(window3, text="Dosyalar Masaüstündeki Hangi klasöre kaydedilsin",justify=LEFT, anchor="w").grid(sticky="W",row=0, column=0)
dosya1 = Entry(window3, width=40)
dosya1.grid(row=0, column=1)
dosya1.focus_set()
Button = ttk.Button(window3, text="Onayla", width=50, command=display_text3)
Button.grid(row=5, column=1)
window3.mainloop()

x1 = x1.replace("B2", string2)
x2 = x2.replace("B2", string2)
x3 = x3.replace("B2", string2)
x4 = x4.replace("B2", string2)
x5 = x5.replace("B2", string2)
x6 = x6.replace("B2", string2)
x7 = x7.replace("B2", string2)
x8 = x8.replace("B2", string2)
x9 = x9.replace("B2", string2)
x10 = x10.replace("B2", string2)
x11 = x11.replace("B2", string2)

x1 = x1.replace("B1", string1)
x2 = x2.replace("B1", string1)
x3 = x3.replace("B1", string1)
x4 = x4.replace("B1", string1)
x5 = x5.replace("B1", string1)
x6 = x6.replace("B1", string1)
x7 = x7.replace("B1", string1)
x8 = x8.replace("B1", string1)
x9 = x9.replace("B1", string1)
x10 = x10.replace("B1", string1)
x11 = x11.replace("B1", string1)

x1 = x1.replace("B3", string3)
x2 = x2.replace("B3", string3)
x3 = x3.replace("B3", string3)
x4 = x4.replace("B3", string3)
x5 = x5.replace("B3", string3)
x6 = x6.replace("B3", string3)
x7 = x7.replace("B3", string3)
x8 = x8.replace("B3", string3)
x9 = x9.replace("B3", string3)
x10 = x10.replace("B3", string3)
x11 = x11.replace("B3", string3)

x1 = x1.replace("B4", string4)
x2 = x2.replace("B4", string4)
x3 = x3.replace("B4", string4)
x4 = x4.replace("B4", string4)
x5 = x5.replace("B4", string4)
x6 = x6.replace("B4", string4)
x7 = x7.replace("B4", string4)
x8 = x8.replace("B4", string4)
x9 = x9.replace("B4", string4)
x10 = x10.replace("B4", string4)
x11 = x11.replace("B4", string3)

x1 = x1.replace("B5", string5)
x2 = x2.replace("B5", string5)
x3 = x3.replace("B5", string5)
x4 = x4.replace("B5", string5)
x5 = x5.replace("B5", string5)
x6 = x6.replace("B5", string5)
x7 = x7.replace("B5", string5)
x8 = x8.replace("B5", string5)
x9 = x9.replace("B5", string5)
x10 = x10.replace("B5", string5)
x11 = x11.replace("B5", string3)

i = 0
x1 = x1.replace("T11", taraf[i])
x2 = x2.replace("T11", taraf[i])
x3 = x3.replace("T11", taraf[i])
x4 = x4.replace("T11", taraf[i])
x5 = x5.replace("T11", taraf[i])
x6 = x6.replace("T11", taraf[i])
x7 = x7.replace("T11", taraf[i])
x8 = x8.replace("T11", taraf[i])
x9 = x9.replace("T11", taraf[i])
x10 = x10.replace("T11", taraf[i])
i = i + 1
x1 = x1.replace("T12", taraf[i])
x2 = x2.replace("T12", taraf[i])
x3 = x3.replace("T12", taraf[i])
x4 = x4.replace("T12", taraf[i])
x5 = x5.replace("T12", taraf[i])
x6 = x6.replace("T12", taraf[i])
x7 = x7.replace("T12", taraf[i])
x8 = x8.replace("T12", taraf[i])
x9 = x9.replace("T12", taraf[i])
x10 = x10.replace("T12", taraf[i])
i = i + 1
x1 = x1.replace("T13", taraf[i])
x2 = x2.replace("T13", taraf[i])
x3 = x3.replace("T13", taraf[i])
x4 = x4.replace("T13", taraf[i])
x5 = x5.replace("T13", taraf[i])
x6 = x6.replace("T13", taraf[i])
x7 = x7.replace("T13", taraf[i])
x8 = x8.replace("T13", taraf[i])
x9 = x9.replace("T13", taraf[i])
x10 = x10.replace("T13", taraf[i])
i = i + 1
x1 = x1.replace("T14", taraf[i])
x2 = x2.replace("T14", taraf[i])
x3 = x3.replace("T14", taraf[i])
x4 = x4.replace("T14", taraf[i])
x5 = x5.replace("T14", taraf[i])
x6 = x6.replace("T14", taraf[i])
x7 = x7.replace("T14", taraf[i])
x8 = x8.replace("T14", taraf[i])
x9 = x9.replace("T14", taraf[i])
x10 = x10.replace("T14", taraf[i])
i = i + 1
x1 = x1.replace("T15", taraf[i])
x2 = x2.replace("T15", taraf[i])
x3 = x3.replace("T15", taraf[i])
x4 = x4.replace("T15", taraf[i])
x5 = x5.replace("T15", taraf[i])
x6 = x6.replace("T15", taraf[i])
x7 = x7.replace("T15", taraf[i])
x8 = x8.replace("T15", taraf[i])
x9 = x9.replace("T15", taraf[i])
x10 = x10.replace("T15", taraf[i])
i = i + 1
x1 = x1.replace("T16", taraf[i])
x2 = x2.replace("T16", taraf[i])
x3 = x3.replace("T16", taraf[i])
x4 = x4.replace("T16", taraf[i])
x5 = x5.replace("T16", taraf[i])
x6 = x6.replace("T16", taraf[i])
x7 = x7.replace("T16", taraf[i])
x8 = x8.replace("T16", taraf[i])
x9 = x9.replace("T16", taraf[i])
x10 = x10.replace("T16", taraf[i])
i = i + 1
x1 = x1.replace("T17", taraf[i])
x2 = x2.replace("T17", taraf[i])
x3 = x3.replace("T17", taraf[i])
x4 = x4.replace("T17", taraf[i])
x5 = x5.replace("T17", taraf[i])
x6 = x6.replace("T17", taraf[i])
x7 = x7.replace("T17", taraf[i])
x8 = x8.replace("T17", taraf[i])
x9 = x9.replace("T17", taraf[i])
x10 = x10.replace("T17", taraf[i])
i = i + 1
x1 = x1.replace("T18", taraf[i])
x2 = x2.replace("T18", taraf[i])
x3 = x3.replace("T18", taraf[i])
x4 = x4.replace("T18", taraf[i])
x5 = x5.replace("T18", taraf[i])
x6 = x6.replace("T18", taraf[i])
x7 = x7.replace("T18", taraf[i])
x8 = x8.replace("T18", taraf[i])
x9 = x9.replace("T18", taraf[i])
x10 = x10.replace("T18", taraf[i])

i = 8
x1 = x1.replace("T21", taraf[i])
x2 = x2.replace("T21", taraf[i])
x3 = x3.replace("T21", taraf[i])
x4 = x4.replace("T21", taraf[i])
x5 = x5.replace("T21", taraf[i])
x6 = x6.replace("T21", taraf[i])
x7 = x7.replace("T21", taraf[i])
x8 = x8.replace("T21", taraf[i])
x9 = x9.replace("T21", taraf[i])
x10 = x10.replace("T21", taraf[i])
x11 = x11.replace("T21", taraf[i])
i = i + 1
x1 = x1.replace("T22", taraf[i])
x2 = x2.replace("T22", taraf[i])
x3 = x3.replace("T22", taraf[i])
x4 = x4.replace("T22", taraf[i])
x5 = x5.replace("T22", taraf[i])
x6 = x6.replace("T22", taraf[i])
x7 = x7.replace("T22", taraf[i])
x8 = x8.replace("T22", taraf[i])
x9 = x9.replace("T22", taraf[i])
x10 = x10.replace("T22", taraf[i])
x11 = x11.replace("T22", taraf[i])
i = i + 1
x1 = x1.replace("T23", taraf[i])
x2 = x2.replace("T23", taraf[i])
x3 = x3.replace("T23", taraf[i])
x4 = x4.replace("T23", taraf[i])
x5 = x5.replace("T23", taraf[i])
x6 = x6.replace("T23", taraf[i])
x7 = x7.replace("T23", taraf[i])
x8 = x8.replace("T23", taraf[i])
x9 = x9.replace("T23", taraf[i])
x10 = x10.replace("T23", taraf[i])
x11 = x11.replace("T13", taraf[i])
i = i + 1
x1 = x1.replace("T24", taraf[i])
x2 = x2.replace("T24", taraf[i])
x3 = x3.replace("T24", taraf[i])
x4 = x4.replace("T24", taraf[i])
x5 = x5.replace("T24", taraf[i])
x6 = x6.replace("T24", taraf[i])
x7 = x7.replace("T24", taraf[i])
x8 = x8.replace("T24", taraf[i])
x9 = x9.replace("T24", taraf[i])
x10 = x10.replace("T24", taraf[i])
x11 = x11.replace("T24", taraf[i])
i = i + 1
x1 = x1.replace("T25", taraf[i])
x2 = x2.replace("T25", taraf[i])
x3 = x3.replace("T25", taraf[i])
x4 = x4.replace("T25", taraf[i])
x5 = x5.replace("T25", taraf[i])
x6 = x6.replace("T25", taraf[i])
x7 = x7.replace("T25", taraf[i])
x8 = x8.replace("T25", taraf[i])
x9 = x9.replace("T25", taraf[i])
x10 = x10.replace("T25", taraf[i])
x11 = x11.replace("T15", taraf[i])
i = i + 1
x1 = x1.replace("T26", taraf[i])
x2 = x2.replace("T26", taraf[i])
x3 = x3.replace("T26", taraf[i])
x4 = x4.replace("T26", taraf[i])
x5 = x5.replace("T26", taraf[i])
x6 = x6.replace("T26", taraf[i])
x7 = x7.replace("T26", taraf[i])
x8 = x8.replace("T26", taraf[i])
x9 = x9.replace("T26", taraf[i])
x10 = x10.replace("T26", taraf[i])
x11 = x11.replace("T26", taraf[i])
i = i + 1
x1 = x1.replace("T27", taraf[i])
x2 = x2.replace("T27", taraf[i])
x3 = x3.replace("T27", taraf[i])
x4 = x4.replace("T27", taraf[i])
x5 = x5.replace("T27", taraf[i])
x6 = x6.replace("T27", taraf[i])
x7 = x7.replace("T27", taraf[i])
x8 = x8.replace("T27", taraf[i])
x9 = x9.replace("T27", taraf[i])
x10 = x10.replace("T27", taraf[i])
x11 = x11.replace("T27", taraf[i])
i = i + 1
x1 = x1.replace("T28", taraf[i])
x2 = x2.replace("T28", taraf[i])
x3 = x3.replace("T28", taraf[i])
x4 = x4.replace("T28", taraf[i])
x5 = x5.replace("T28", taraf[i])
x6 = x6.replace("T28", taraf[i])
x7 = x7.replace("T28", taraf[i])
x8 = x8.replace("T28", taraf[i])
x9 = x9.replace("T28", taraf[i])
x10 = x10.replace("T28", taraf[i])
x11 = x11.replace("T28", taraf[i])
if (len(taraf) > 23):
    i = 16
    x1 = x1.replace("T31", taraf[i])
    x2 = x2.replace("T31", taraf[i])
    x3 = x3.replace("T31", taraf[i])
    x4 = x4.replace("T31", taraf[i])
    x5 = x5.replace("T31", taraf[i])
    x6 = x6.replace("T31", taraf[i])
    x7 = x7.replace("T31", taraf[i])
    x8 = x8.replace("T31", taraf[i])
    x9 = x9.replace("T31", taraf[i])
    x10 = x10.replace("T11", taraf[i])
    i = i + 1
    x1 = x1.replace("T32", taraf[i])
    x2 = x2.replace("T32", taraf[i])
    x3 = x3.replace("T32", taraf[i])
    x4 = x4.replace("T32", taraf[i])
    x5 = x5.replace("T32", taraf[i])
    x6 = x6.replace("T32", taraf[i])
    x7 = x7.replace("T32", taraf[i])
    x8 = x8.replace("T32", taraf[i])
    x9 = x9.replace("T32", taraf[i])
    x10 = x10.replace("T12", taraf[i])
    i = i + 1
    x1 = x1.replace("T33", taraf[i])
    x2 = x2.replace("T33", taraf[i])
    x3 = x3.replace("T33", taraf[i])
    x4 = x4.replace("T33", taraf[i])
    x5 = x5.replace("T33", taraf[i])
    x6 = x6.replace("T33", taraf[i])
    x7 = x7.replace("T33", taraf[i])
    x8 = x8.replace("T33", taraf[i])
    x9 = x9.replace("T33", taraf[i])
    x10 = x10.replace("T33", taraf[i])
    i = i + 1
    x1 = x1.replace("T34", taraf[i])
    x2 = x2.replace("T34", taraf[i])
    x3 = x3.replace("T34", taraf[i])
    x4 = x4.replace("T34", taraf[i])
    x5 = x5.replace("T34", taraf[i])
    x6 = x6.replace("T34", taraf[i])
    x7 = x7.replace("T34", taraf[i])
    x8 = x8.replace("T34", taraf[i])
    x9 = x9.replace("T34", taraf[i])
    x10 = x10.replace("T14", taraf[i])
    i = i + 1
    x1 = x1.replace("T35", taraf[i])
    x2 = x2.replace("T35", taraf[i])
    x3 = x3.replace("T35", taraf[i])
    x4 = x4.replace("T35", taraf[i])
    x5 = x5.replace("T35", taraf[i])
    x6 = x6.replace("T35", taraf[i])
    x7 = x7.replace("T35", taraf[i])
    x8 = x8.replace("T35", taraf[i])
    x9 = x9.replace("T35", taraf[i])
    x10 = x10.replace("T15", taraf[i])
    i = i + 1
    x1 = x1.replace("T36", taraf[i])
    x2 = x2.replace("T36", taraf[i])
    x3 = x3.replace("T36", taraf[i])
    x4 = x4.replace("T36", taraf[i])
    x5 = x5.replace("T36", taraf[i])
    x6 = x6.replace("T36", taraf[i])
    x7 = x7.replace("T36", taraf[i])
    x8 = x8.replace("T36", taraf[i])
    x9 = x9.replace("T36", taraf[i])
    x10 = x10.replace("T16", taraf[i])
    i = i + 1
    x1 = x1.replace("T37", taraf[i])
    x2 = x2.replace("T37", taraf[i])
    x3 = x3.replace("T37", taraf[i])
    x4 = x4.replace("T37", taraf[i])
    x5 = x5.replace("T37", taraf[i])
    x6 = x6.replace("T37", taraf[i])
    x7 = x7.replace("T37", taraf[i])
    x8 = x8.replace("T37", taraf[i])
    x9 = x9.replace("T37", taraf[i])
    x10 = x10.replace("T37", taraf[i])
    i = i + 1
    x1 = x1.replace("T38", taraf[i])
    x2 = x2.replace("T38", taraf[i])
    x3 = x3.replace("T38", taraf[i])
    x4 = x4.replace("T38", taraf[i])
    x5 = x5.replace("T38", taraf[i])
    x6 = x6.replace("T38", taraf[i])
    x7 = x7.replace("T38", taraf[i])
    x8 = x8.replace("T38", taraf[i])
    x9 = x9.replace("T38", taraf[i])
    x10 = x10.replace("T38", taraf[i])
if (len(taraf) > 31):
    i = 24
    x1 = x1.replace("T41", taraf[i])
    x2 = x2.replace("T41", taraf[i])
    x3 = x3.replace("T41", taraf[i])
    x4 = x4.replace("T41", taraf[i])
    x5 = x5.replace("T41", taraf[i])
    x6 = x6.replace("T41", taraf[i])
    x7 = x7.replace("T41", taraf[i])
    x8 = x8.replace("T41", taraf[i])
    x9 = x9.replace("T41", taraf[i])
    x10 = x10.replace("T41", taraf[i])
    i = i + 1
    x1 = x1.replace("T42", taraf[i])
    x2 = x2.replace("T42", taraf[i])
    x3 = x3.replace("T42", taraf[i])
    x4 = x4.replace("T42", taraf[i])
    x5 = x5.replace("T42", taraf[i])
    x6 = x6.replace("T42", taraf[i])
    x7 = x7.replace("T42", taraf[i])
    x8 = x8.replace("T42", taraf[i])
    x9 = x9.replace("T42", taraf[i])
    x10 = x10.replace("T42", taraf[i])
    i = i + 1
    x1 = x1.replace("T43", taraf[i])
    x2 = x2.replace("T43", taraf[i])
    x3 = x3.replace("T43", taraf[i])
    x4 = x4.replace("T43", taraf[i])
    x5 = x5.replace("T43", taraf[i])
    x6 = x6.replace("T43", taraf[i])
    x7 = x7.replace("T43", taraf[i])
    x8 = x8.replace("T43", taraf[i])
    x9 = x9.replace("T43", taraf[i])
    x10 = x10.replace("T43", taraf[i])
    i = i + 1
    x1 = x1.replace("T44", taraf[i])
    x2 = x2.replace("T44", taraf[i])
    x3 = x3.replace("T44", taraf[i])
    x4 = x4.replace("T44", taraf[i])
    x5 = x5.replace("T44", taraf[i])
    x6 = x6.replace("T44", taraf[i])
    x7 = x7.replace("T44", taraf[i])
    x8 = x8.replace("T44", taraf[i])
    x9 = x9.replace("T44", taraf[i])
    x10 = x10.replace("T44", taraf[i])
    i = i + 1
    x1 = x1.replace("T45", taraf[i])
    x2 = x2.replace("T45", taraf[i])
    x3 = x3.replace("T45", taraf[i])
    x4 = x4.replace("T45", taraf[i])
    x5 = x5.replace("T45", taraf[i])
    x6 = x6.replace("T45", taraf[i])
    x7 = x7.replace("T45", taraf[i])
    x8 = x8.replace("T45", taraf[i])
    x9 = x9.replace("T45", taraf[i])
    x10 = x10.replace("T45", taraf[i])
    i = i + 1
    x1 = x1.replace("T46", taraf[i])
    x2 = x2.replace("T46", taraf[i])
    x3 = x3.replace("T46", taraf[i])
    x4 = x4.replace("T46", taraf[i])
    x5 = x5.replace("T46", taraf[i])
    x6 = x6.replace("T46", taraf[i])
    x7 = x7.replace("T46", taraf[i])
    x8 = x8.replace("T46", taraf[i])
    x9 = x9.replace("T46", taraf[i])
    x10 = x10.replace("T46", taraf[i])
    i = i + 1
    x1 = x1.replace("T47", taraf[i])
    x2 = x2.replace("T47", taraf[i])
    x3 = x3.replace("T47", taraf[i])
    x4 = x4.replace("T47", taraf[i])
    x5 = x5.replace("T47", taraf[i])
    x6 = x6.replace("T47", taraf[i])
    x7 = x7.replace("T47", taraf[i])
    x8 = x8.replace("T47", taraf[i])
    x9 = x9.replace("T47", taraf[i])
    x10 = x10.replace("T47", taraf[i])
    i = i + 1
    x1 = x1.replace("T48", taraf[i])
    x2 = x2.replace("T48", taraf[i])
    x3 = x3.replace("T48", taraf[i])
    x4 = x4.replace("T48", taraf[i])
    x5 = x5.replace("T48", taraf[i])
    x6 = x6.replace("T48", taraf[i])
    x7 = x7.replace("T48", taraf[i])
    x8 = x8.replace("T48", taraf[i])
    x9 = x9.replace("T48", taraf[i])
    x10 = x10.replace("T48", taraf[i])
if (len(taraf) > 39):
    i = 32
    x1 = x1.replace("T51", taraf[i])
    x2 = x2.replace("T51", taraf[i])
    x3 = x3.replace("T51", taraf[i])
    x4 = x4.replace("T51", taraf[i])
    x5 = x5.replace("T51", taraf[i])
    x6 = x6.replace("T51", taraf[i])
    x7 = x7.replace("T51", taraf[i])
    x8 = x8.replace("T51", taraf[i])
    x9 = x9.replace("T51", taraf[i])
    x10 = x10.replace("T51", taraf[i])
    i = i + 1
    x1 = x1.replace("T52", taraf[i])
    x2 = x2.replace("T52", taraf[i])
    x3 = x3.replace("T52", taraf[i])
    x4 = x4.replace("T52", taraf[i])
    x5 = x5.replace("T52", taraf[i])
    x6 = x6.replace("T52", taraf[i])
    x7 = x7.replace("T52", taraf[i])
    x8 = x8.replace("T52", taraf[i])
    x9 = x9.replace("T52", taraf[i])
    x10 = x10.replace("T52", taraf[i])
    i = i + 1
    x1 = x1.replace("T53", taraf[i])
    x2 = x2.replace("T53", taraf[i])
    x3 = x3.replace("T53", taraf[i])
    x4 = x4.replace("T53", taraf[i])
    x5 = x5.replace("T53", taraf[i])
    x6 = x6.replace("T53", taraf[i])
    x7 = x7.replace("T53", taraf[i])
    x8 = x8.replace("T53", taraf[i])
    x9 = x9.replace("T53", taraf[i])
    x10 = x10.replace("T53", taraf[i])
    i = i + 1
    x1 = x1.replace("T54", taraf[i])
    x2 = x2.replace("T54", taraf[i])
    x3 = x3.replace("T54", taraf[i])
    x4 = x4.replace("T54", taraf[i])
    x5 = x5.replace("T54", taraf[i])
    x6 = x6.replace("T54", taraf[i])
    x7 = x7.replace("T54", taraf[i])
    x8 = x8.replace("T54", taraf[i])
    x9 = x9.replace("T54", taraf[i])
    x10 = x10.replace("T54", taraf[i])
    i = i + 1
    x1 = x1.replace("T55", taraf[i])
    x2 = x2.replace("T55", taraf[i])
    x3 = x3.replace("T55", taraf[i])
    x4 = x4.replace("T55", taraf[i])
    x5 = x5.replace("T55", taraf[i])
    x6 = x6.replace("T55", taraf[i])
    x7 = x7.replace("T55", taraf[i])
    x8 = x8.replace("T55", taraf[i])
    x9 = x9.replace("T55", taraf[i])
    x10 = x10.replace("T55", taraf[i])
    i = i + 1
    x1 = x1.replace("T56", taraf[i])
    x2 = x2.replace("T56", taraf[i])
    x3 = x3.replace("T56", taraf[i])
    x4 = x4.replace("T56", taraf[i])
    x5 = x5.replace("T56", taraf[i])
    x6 = x6.replace("T56", taraf[i])
    x7 = x7.replace("T56", taraf[i])
    x8 = x8.replace("T56", taraf[i])
    x9 = x9.replace("T56", taraf[i])
    x10 = x10.replace("T56", taraf[i])
    i = i + 1
    x1 = x1.replace("T57", taraf[i])
    x2 = x2.replace("T57", taraf[i])
    x3 = x3.replace("T57", taraf[i])
    x4 = x4.replace("T57", taraf[i])
    x5 = x5.replace("T57", taraf[i])
    x6 = x6.replace("T57", taraf[i])
    x7 = x7.replace("T57", taraf[i])
    x8 = x8.replace("T57", taraf[i])
    x9 = x9.replace("T57", taraf[i])
    x10 = x10.replace("T57", taraf[i])
    i = i + 1
    x1 = x1.replace("T58", taraf[i])
    x2 = x2.replace("T58", taraf[i])
    x3 = x3.replace("T58", taraf[i])
    x4 = x4.replace("T58", taraf[i])
    x5 = x5.replace("T58", taraf[i])
    x6 = x6.replace("T58", taraf[i])
    x7 = x7.replace("T58", taraf[i])
    x8 = x8.replace("T58", taraf[i])
    x9 = x9.replace("T58", taraf[i])
    x10 = x10.replace("T58", taraf[i])


x1 = x1.replace("G1", aaa1)
x2 = x2.replace("G1", aaa1)
x3 = x3.replace("G1", aaa1)
x4 = x4.replace("G1", aaa1)
x5 = x5.replace("G1", aaa1)
x6 = x6.replace("G1", aaa1)
x7 = x7.replace("G1", aaa1)
x8 = x8.replace("G1", aaa1)
x9 = x9.replace("G1", aaa1)
x10 = x10.replace("G1", aaa1)
x11 = x11.replace("G1", aaa1)

x1 = x1.replace("G2", aaa2)
x2 = x2.replace("G2", aaa2)
x3 = x3.replace("G2", aaa2)
x4 = x4.replace("G2", aaa2)
x5 = x5.replace("G2", aaa2)
x6 = x6.replace("G2", aaa2)
x7 = x7.replace("G2", aaa2)
x8 = x8.replace("G2", aaa2)
x9 = x9.replace("G2", aaa2)
x10 = x10.replace("G2", aaa2)
x11 = x11.replace("G2", aaa2)

x1 = x1.replace("G3", aaa3)
x2 = x2.replace("G3", aaa3)
x3 = x3.replace("G3", aaa3)
x4 = x4.replace("G3", aaa3)
x5 = x5.replace("G3", aaa3)
x6 = x6.replace("G3", aaa3)
x7 = x7.replace("G3", aaa3)
x8 = x8.replace("G3", aaa3)
x9 = x9.replace("G3", aaa3)
x10 = x10.replace("G3", aaa3)
x11 = x11.replace("G3", aaa3)

x1 = x1.replace("G4", aaa4)
x2 = x2.replace("G4", aaa4)
x3 = x3.replace("G4", aaa4)
x4 = x4.replace("G4", aaa4)
x5 = x5.replace("G4", aaa4)
x6 = x6.replace("G4", aaa4)
x7 = x7.replace("G4", aaa4)
x8 = x8.replace("G4", aaa4)
x9 = x9.replace("G4", aaa4)
x10 = x10.replace("G4", aaa4)
x11 = x11.replace("G4", aaa4)

x1 = x1.replace("G5", aaa5)
x2 = x2.replace("G5", aaa5)
x3 = x3.replace("G5", aaa5)
x4 = x4.replace("G5", aaa5)
x5 = x5.replace("G5", aaa5)
x6 = x6.replace("G5", aaa5)
x7 = x7.replace("G5", aaa5)
x8 = x8.replace("G5", aaa5)
x9 = x9.replace("G5", aaa5)
x10 = x10.replace("G5", aaa5)
x11 = x11.replace("G5", aaa5)

desktop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')
dosyayolu = ((desktop + dosyasss))

doc = docx.Document()
doc.add_paragraph(x1)
doc.save(join(dosyayolu, "1.DAVET MEKTUBU1.docx"))

doc2 = docx.Document()
doc2.add_paragraph(x2)
doc2.save(join(dosyayolu, "2.BİLGİLENDİRME TUTANAĞI1.docx"))

doc3 = docx.Document()
doc3.add_paragraph(x3)
doc3.save(join(dosyayolu, "3.İLK OTURUM TUTANAĞI1.docx"))

doc4 = docx.Document()
doc4.add_paragraph(x4)
doc4.save(join(dosyayolu, "4.İKİNCİ OTURUM TUTANAĞI1.docx"))

doc5 = docx.Document()
doc5.add_paragraph(x5)
doc5.save(join(dosyayolu, "5.ANLAŞMA BELGESİ1.docx"))

doc6 = docx.Document()
doc6.add_paragraph(x6)
doc6.save(join(dosyayolu, "6.SON TUTANAK1.docx"))

doc7 = docx.Document()
doc7.add_paragraph(x7)
doc7.save(join(dosyayolu, "7.ARABULUCULUK SON TUTANAK GÖNDERİMİ ÜST YAZI1.docx"))

doc8 = docx.Document()
doc8.add_paragraph(x8)
doc8.save(join(dosyayolu, "8.ARABULUCULUK BÜRO  ÖDEME ÜST YAZI1.docx"))

doc9 = docx.Document()
doc9.add_paragraph(x9)
doc9.save(join(dosyayolu, "9.ÖRNEK MAKBUZ1.docx"))

doc10 = docx.Document()
doc10.add_paragraph(x10)
doc10.save(join(dosyayolu, "10.ÜCRET SÖZLEŞMESİ1.docx"))

doc11 = docx.Document()
doc11.add_paragraph(x11)
doc11.save(join(dosyayolu, "12.DAVET MEKTUBU1.docx"))













